# For scripted languages it might be unnecessary to change anything except the line below `run:`
# Please keep in mind, that whatever you do, <TAB> characters need to stay intact!

build:
	true # commands to create your binary/executable                                                            

clean:
	true # commands to clean buildartifacts                                                                     

rebuild: clean build

run:
	@php7.0 ../php5_6/wordcount.php
